const actions = {
  GET_HUMANS_BEGIN: 'GET_HUMANS_BEGIN',
  GET_HUMANS_SUCCESS: 'GET_HUMANS_SUCCESS',
  GET_HUMANS_ERROR: 'GET_HUMANS_ERROR',

  GET_HUMAN_DETAIL_BEGIN: 'GET_HUMAN_DETAIL_BEGIN',
  GET_HUMAN_DETAIL_SUCCESS: 'GET_HUMAN_DETAIL_SUCCESS',
  GET_HUMAN_DETAIL_ERROR: 'GET_HUMAN_DETAIL_ERROR',

  CREATE_HUMAN_BEGIN: 'CREATE_HUMAN_BEGIN',
  CREATE_HUMAN_SUCCESS: 'CREATE_HUMAN_SUCCESS',
  CREATE_HUMAN_ERROR: 'CREATE_HUMAN_ERROR',

  DELETE_HUMAN_BEGIN: 'DELETE_HUMAN_BEGIN',
  DELETE_HUMAN_SUCCESS: 'DELETE_HUMAN_SUCCESS',
  DELETE_HUMAN_ERROR: 'DELETE_HUMAN_ERROR',
};

export default actions;
